/*
 * File: app/view/Detail.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Kiva.view.Detail', {
    extend: 'Ext.Panel',
    alias: 'widget.detail',

    requires: [
        'Kiva.view.detail.Information',
        'Kiva.view.detail.Schedule',
        'Kiva.view.detail.Map'
    ],

    config: {
        bottom: 0,
        right: 0,
        top: 0,
        ui: 'detail',
        width: 400,
        hideOnMaskTap: true,
        layout: {
            type: 'vbox'
        },
        modal: true,
        loan: null,
        items: [
            {
                xtype: 'carousel',
                flex: 1,
                items: [
                    {
                        xtype: 'detailInformation'
                    },
                    {
                        xtype: 'detailSchedule'
                    },
                    {
                        xtype: 'detailMap'
                    }
                ]
            },
            {
                xtype: 'button',
                id: 'lendButton',
                text: 'Lend $25'
            }
        ],
        listeners: [
            {
                fn: 'onPanelInitialize',
                event: 'initialize'
            }
        ]
    },

    onPanelInitialize: function(component, options) {
        this.setBaseCls(Ext.baseCSSPrefix + 'sheet');
    },

    hide: function(animation) {

        var me = this;

        //we fire this event so the controller can deselect all items immediately.
        me.fireEvent('hideanimationstart', me);

        //show the mask again
        me.callParent();

    },

    updateLoan: function(newLoan) {
        var carousel = this.down('carousel'),
            information = this.down('detailInformation'),
            payments = this.down('detailSchedule'),
            map = this.down('detailMap'),
            coords = newLoan.get('location').geo.pairs.split(' ').map(parseFloat);

        information.setData(newLoan.data);
        payments.setData(newLoan.data.terms.scheduled_payments);

        //update the lend button
        this.updateLendButton();

        //update the map
        if (this.mapMarker) {
            this.mapMarker.setMap(null);
            delete this.mapMarker;
        }

        //add a marker for the Loanee's position on the map
        this.mapMarker = new google.maps.Marker({
            map: map.map,
            title : newLoan.get('name'),
            position: new google.maps.LatLng(coords[0], coords[1])
        });

        carousel.setActiveItem(0);

        map.setMapCenter(this.mapMarker.position);
    },

    updateLendButton: function() {

        var url    = "http://www.kiva.org/lend/" + this.getLoan().getId(),
            button = this.down('button');
        button.on('tap', function(){
            window.open(url);
        });

        /*

        link = Ext.getDom('linker'),
        clickEvent = document.createEvent('Event');


        http://www.sencha.com/forum/showthread.php?130358-window.open()-from-toolbar-button-opens-window-from-list-item-a-new-tab&p=639938#post639938

        clickEvent.initEvent('click', true, false);

        button.setHandler(function() {
        link.href = url;
        link.dispatchEvent(clickEvent);
        });*/
    }

});