/*
 * File: app/view/LoanFilter.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Kiva.view.LoanFilter', {
    extend: 'Ext.Container',
    alias: 'widget.loanfilter',

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                ui: 'green',
                title: 'Kiva',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        iconCls: 'refresh',
                        iconMask: true
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                ui: 'gray',
                items: [
                    {
                        xtype: 'selectfield',
                        name: 'gender',
                        options: [
                            {
                                text: 'Both',
                                value: 'both'
                            },
                            {
                                text: 'Male',
                                value: 'male'
                            },
                            {
                                text: 'Female',
                                value: 'female'
                            }
                        ]
                    },
                    {
                        xtype: 'selectfield',
                        name: 'sector',
                        options: [
                            {
                                text: 'All',
                                value: ''
                            },
                            {
                                text: 'Agriculture',
                                value: 'agriculture'
                            },
                            {
                                text: 'Transportation',
                                value: 'transportation'
                            },
                            {
                                text: 'Services',
                                value: 'services'
                            },
                            {
                                text: 'Clothing',
                                value: 'clothing'
                            },
                            {
                                text: 'Health',
                                value: 'health'
                            },
                            {
                                text: 'Retail',
                                value: 'retail'
                            },
                            {
                                text: 'Manufacturing',
                                value: 'manufacturing'
                            },
                            {
                                text: 'Arts',
                                value: 'arts'
                            },
                            {
                                text: 'Housing',
                                value: 'housing'
                            },
                            {
                                text: 'Food',
                                value: 'food'
                            },
                            {
                                text: 'Wholesale',
                                value: 'wholesale'
                            },
                            {
                                text: 'Construction',
                                value: 'construction'
                            },
                            {
                                text: 'Education',
                                value: 'education'
                            },
                            {
                                text: 'Personal Use',
                                value: 'personal'
                            },
                            {
                                text: 'Entertainment',
                                value: 'entertainment'
                            },
                            {
                                text: 'Green',
                                value: 'green'
                            }
                        ]
                    },
                    {
                        xtype: 'selectfield',
                        name: 'sort_by',
                        options: [
                            {
                                text: 'Newest',
                                value: 'newest'
                            },
                            {
                                text: 'Oldest',
                                value: 'oldest'
                            },
                            {
                                text: 'Expiring',
                                value: 'expiration'
                            },
                            {
                                text: 'Amount Remaining',
                                value: 'amount_remaining'
                            },
                            {
                                text: 'Popularity',
                                value: 'popularity'
                            },
                            {
                                text: 'Loan Amount',
                                value: 'loan_amount'
                            }
                        ]
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'searchfield'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onContainerInitialize',
                event: 'initialize'
            }
        ]
    },

    onContainerInitialize: function(component, options) {
        if (Ext.os.deviceType === 'Phone'){
            this.setItems([
            { xtype: 'searchfield', flex: 1 }
            ]);
        }
    },

    onFieldChange: function(comp, value) {
        this.fireAction('filter', this.getValues(), this);
    }

});