
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "touch/src",
  "Ext.data.proxy.Kiva": "lib/KivaProxy.js",
  "Ext.data.proxy.Sql": "touch/src/data/proxy/SQL.js",
  "Ext.device.Purchases.Product": "touch/src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "touch/src/device/purchases/Sencha.js",
  "Kiva": "app"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.AbstractComponent": [],
  "Ext.AbstractManager": [],
  "Ext.ActionSheet": [],
  "Ext.Ajax": [],
  "Ext.Anim": [],
  "Ext.Audio": [],
  "Ext.Button": [],
  "Ext.Component": [
    "Ext.lib.Component"
  ],
  "Ext.ComponentManager": [
    "Ext.ComponentMgr"
  ],
  "Ext.ComponentQuery": [],
  "Ext.Container": [
    "Ext.lib.Container"
  ],
  "Ext.Decorator": [],
  "Ext.Evented": [
    "Ext.EventedBase"
  ],
  "Ext.Img": [],
  "Ext.ItemCollection": [],
  "Ext.Label": [],
  "Ext.LoadMask": [],
  "Ext.Map": [],
  "Ext.Mask": [],
  "Ext.Media": [],
  "Ext.MessageBox": [],
  "Ext.Panel": [
    "Ext.lib.Panel"
  ],
  "Ext.SegmentedButton": [],
  "Ext.Sheet": [],
  "Ext.Sortable": [],
  "Ext.Spacer": [],
  "Ext.TaskQueue": [],
  "Ext.Template": [],
  "Ext.Title": [],
  "Ext.TitleBar": [],
  "Ext.Toolbar": [],
  "Ext.Video": [],
  "Ext.XTemplate": [],
  "Ext.XTemplateCompiler": [],
  "Ext.XTemplateParser": [],
  "Ext.app.Action": [],
  "Ext.app.Application": [],
  "Ext.app.Controller": [],
  "Ext.app.History": [],
  "Ext.app.Profile": [],
  "Ext.app.Route": [],
  "Ext.app.Router": [],
  "Ext.bb.CrossCut": [],
  "Ext.behavior.Behavior": [],
  "Ext.behavior.Draggable": [],
  "Ext.behavior.Scrollable": [],
  "Ext.behavior.Translatable": [],
  "Ext.carousel.Carousel": [
    "Ext.Carousel"
  ],
  "Ext.carousel.Indicator": [
    "Ext.Carousel.Indicator"
  ],
  "Ext.carousel.Infinite": [],
  "Ext.carousel.Item": [],
  "Ext.data.ArrayStore": [],
  "Ext.data.Batch": [],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [],
  "Ext.data.Error": [],
  "Ext.data.Errors": [],
  "Ext.data.Field": [],
  "Ext.data.JsonP": [
    "Ext.util.JSONP"
  ],
  "Ext.data.JsonStore": [],
  "Ext.data.Model": [
    "Ext.data.Record"
  ],
  "Ext.data.ModelManager": [
    "Ext.ModelMgr",
    "Ext.ModelManager"
  ],
  "Ext.data.NodeInterface": [
    "Ext.data.Node"
  ],
  "Ext.data.NodeStore": [],
  "Ext.data.Operation": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [],
  "Ext.data.StoreManager": [
    "Ext.StoreMgr",
    "Ext.data.StoreMgr",
    "Ext.StoreManager"
  ],
  "Ext.data.TreeStore": [],
  "Ext.data.Types": [],
  "Ext.data.Validations": [
    "Ext.data.validations"
  ],
  "Ext.data.association.Association": [
    "Ext.data.Association"
  ],
  "Ext.data.association.BelongsTo": [
    "Ext.data.BelongsToAssociation"
  ],
  "Ext.data.association.HasMany": [
    "Ext.data.HasManyAssociation"
  ],
  "Ext.data.association.HasOne": [
    "Ext.data.HasOneAssociation"
  ],
  "Ext.data.identifier.Sequential": [],
  "Ext.data.identifier.Simple": [],
  "Ext.data.identifier.Uuid": [],
  "Ext.data.proxy.Ajax": [
    "Ext.data.HttpProxy",
    "Ext.data.AjaxProxy"
  ],
  "Ext.data.proxy.Client": [
    "Ext.proxy.ClientProxy"
  ],
  "Ext.data.proxy.Direct": [
    "Ext.data.DirectProxy"
  ],
  "Ext.data.proxy.JsonP": [
    "Ext.data.ScriptTagProxy"
  ],
  "Ext.data.proxy.Kiva": [],
  "Ext.data.proxy.LocalStorage": [
    "Ext.data.LocalStorageProxy"
  ],
  "Ext.data.proxy.Memory": [
    "Ext.data.MemoryProxy"
  ],
  "Ext.data.proxy.Proxy": [
    "Ext.data.DataProxy",
    "Ext.data.Proxy"
  ],
  "Ext.data.proxy.Rest": [
    "Ext.data.RestProxy"
  ],
  "Ext.data.proxy.Server": [
    "Ext.data.ServerProxy"
  ],
  "Ext.data.proxy.SessionStorage": [
    "Ext.data.SessionStorageProxy"
  ],
  "Ext.data.proxy.Sql": [
    "Ext.data.proxy.SQL"
  ],
  "Ext.data.proxy.WebStorage": [
    "Ext.data.WebStorageProxy"
  ],
  "Ext.data.reader.Array": [
    "Ext.data.ArrayReader"
  ],
  "Ext.data.reader.Json": [
    "Ext.data.JsonReader"
  ],
  "Ext.data.reader.Reader": [
    "Ext.data.Reader",
    "Ext.data.DataReader"
  ],
  "Ext.data.reader.Xml": [
    "Ext.data.XmlReader"
  ],
  "Ext.data.writer.Json": [
    "Ext.data.JsonWriter"
  ],
  "Ext.data.writer.Writer": [
    "Ext.data.DataWriter",
    "Ext.data.Writer"
  ],
  "Ext.data.writer.Xml": [
    "Ext.data.XmlWriter"
  ],
  "Ext.dataview.DataView": [
    "Ext.DataView"
  ],
  "Ext.dataview.IndexBar": [
    "Ext.IndexBar"
  ],
  "Ext.dataview.List": [
    "Ext.List"
  ],
  "Ext.dataview.ListItemHeader": [],
  "Ext.dataview.NestedList": [
    "Ext.NestedList"
  ],
  "Ext.dataview.component.Container": [],
  "Ext.dataview.component.DataItem": [],
  "Ext.dataview.component.ListItem": [],
  "Ext.dataview.element.Container": [],
  "Ext.dataview.element.List": [],
  "Ext.device.Camera": [],
  "Ext.device.Communicator": [],
  "Ext.device.Connection": [],
  "Ext.device.Contacts": [],
  "Ext.device.Device": [],
  "Ext.device.Geolocation": [],
  "Ext.device.Notification": [],
  "Ext.device.Orientation": [],
  "Ext.device.Purchases": [],
  "Ext.device.Purchases.Product": [],
  "Ext.device.Purchases.Purchase": [],
  "Ext.device.Push": [],
  "Ext.device.camera.Abstract": [],
  "Ext.device.camera.PhoneGap": [],
  "Ext.device.camera.Sencha": [],
  "Ext.device.camera.Simulator": [],
  "Ext.device.communicator.Android": [],
  "Ext.device.communicator.Default": [],
  "Ext.device.connection.Abstract": [],
  "Ext.device.connection.PhoneGap": [],
  "Ext.device.connection.Sencha": [],
  "Ext.device.connection.Simulator": [],
  "Ext.device.contacts.Abstract": [],
  "Ext.device.contacts.Sencha": [],
  "Ext.device.device.Abstract": [],
  "Ext.device.device.PhoneGap": [],
  "Ext.device.device.Sencha": [],
  "Ext.device.device.Simulator": [],
  "Ext.device.geolocation.Abstract": [],
  "Ext.device.geolocation.Sencha": [],
  "Ext.device.geolocation.Simulator": [],
  "Ext.device.notification.Abstract": [],
  "Ext.device.notification.PhoneGap": [],
  "Ext.device.notification.Sencha": [],
  "Ext.device.notification.Simulator": [],
  "Ext.device.orientation.Abstract": [],
  "Ext.device.orientation.HTML5": [],
  "Ext.device.orientation.Sencha": [],
  "Ext.device.purchases.Sencha": [],
  "Ext.device.push.Abstract": [],
  "Ext.device.push.Sencha": [],
  "Ext.direct.Event": [],
  "Ext.direct.ExceptionEvent": [],
  "Ext.direct.JsonProvider": [],
  "Ext.direct.Manager": [
    "Ext.Direct"
  ],
  "Ext.direct.PollingProvider": [],
  "Ext.direct.Provider": [],
  "Ext.direct.RemotingEvent": [],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [],
  "Ext.direct.Transaction": [
    "Ext.Direct.Transaction"
  ],
  "Ext.dom.CompositeElement": [
    "Ext.CompositeElement"
  ],
  "Ext.event.Controller": [],
  "Ext.event.Dispatcher": [],
  "Ext.event.Dom": [],
  "Ext.event.Event": [
    "Ext.EventObject"
  ],
  "Ext.event.ListenerStack": [],
  "Ext.event.Touch": [],
  "Ext.event.publisher.ComponentDelegation": [],
  "Ext.event.publisher.ComponentPaint": [],
  "Ext.event.publisher.ComponentSize": [],
  "Ext.event.publisher.Dom": [],
  "Ext.event.publisher.ElementPaint": [],
  "Ext.event.publisher.ElementSize": [],
  "Ext.event.publisher.Publisher": [],
  "Ext.event.publisher.TouchGesture": [],
  "Ext.event.recognizer.DoubleTap": [],
  "Ext.event.recognizer.Drag": [],
  "Ext.event.recognizer.HorizontalSwipe": [],
  "Ext.event.recognizer.LongPress": [],
  "Ext.event.recognizer.MultiTouch": [],
  "Ext.event.recognizer.Pinch": [],
  "Ext.event.recognizer.Recognizer": [],
  "Ext.event.recognizer.Rotate": [],
  "Ext.event.recognizer.SingleTouch": [],
  "Ext.event.recognizer.Swipe": [],
  "Ext.event.recognizer.Tap": [],
  "Ext.event.recognizer.Touch": [],
  "Ext.event.recognizer.VerticalSwipe": [],
  "Ext.field.Checkbox": [
    "Ext.form.Checkbox"
  ],
  "Ext.field.DatePicker": [
    "Ext.form.DatePicker"
  ],
  "Ext.field.Email": [
    "Ext.form.Email"
  ],
  "Ext.field.Field": [
    "Ext.form.Field"
  ],
  "Ext.field.File": [],
  "Ext.field.Hidden": [
    "Ext.form.Hidden"
  ],
  "Ext.field.Input": [],
  "Ext.field.Number": [
    "Ext.form.Number"
  ],
  "Ext.field.Password": [
    "Ext.form.Password"
  ],
  "Ext.field.Radio": [
    "Ext.form.Radio"
  ],
  "Ext.field.Search": [
    "Ext.form.Search"
  ],
  "Ext.field.Select": [
    "Ext.form.Select"
  ],
  "Ext.field.Slider": [
    "Ext.form.Slider"
  ],
  "Ext.field.Spinner": [
    "Ext.form.Spinner"
  ],
  "Ext.field.Text": [
    "Ext.form.Text"
  ],
  "Ext.field.TextArea": [
    "Ext.form.TextArea"
  ],
  "Ext.field.TextAreaInput": [],
  "Ext.field.Toggle": [
    "Ext.form.Toggle"
  ],
  "Ext.field.Url": [
    "Ext.form.Url"
  ],
  "Ext.form.FieldSet": [],
  "Ext.form.Panel": [
    "Ext.form.FormPanel"
  ],
  "Ext.fx.Animation": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Runner": [],
  "Ext.fx.State": [],
  "Ext.fx.animation.Abstract": [],
  "Ext.fx.animation.Cube": [],
  "Ext.fx.animation.Fade": [
    "Ext.fx.animation.FadeIn"
  ],
  "Ext.fx.animation.FadeOut": [],
  "Ext.fx.animation.Flip": [],
  "Ext.fx.animation.Pop": [
    "Ext.fx.animation.PopIn"
  ],
  "Ext.fx.animation.PopOut": [],
  "Ext.fx.animation.Slide": [
    "Ext.fx.animation.SlideIn"
  ],
  "Ext.fx.animation.SlideOut": [],
  "Ext.fx.animation.Wipe": [
    "Ext.fx.animation.WipeIn"
  ],
  "Ext.fx.animation.WipeOut": [],
  "Ext.fx.easing.Abstract": [],
  "Ext.fx.easing.Bounce": [],
  "Ext.fx.easing.BoundMomentum": [],
  "Ext.fx.easing.EaseIn": [],
  "Ext.fx.easing.EaseOut": [],
  "Ext.fx.easing.Linear": [],
  "Ext.fx.easing.Momentum": [],
  "Ext.fx.layout.Card": [],
  "Ext.fx.layout.card.Abstract": [],
  "Ext.fx.layout.card.Cover": [],
  "Ext.fx.layout.card.Cube": [],
  "Ext.fx.layout.card.Fade": [],
  "Ext.fx.layout.card.Flip": [],
  "Ext.fx.layout.card.Pop": [],
  "Ext.fx.layout.card.Reveal": [],
  "Ext.fx.layout.card.Scroll": [],
  "Ext.fx.layout.card.ScrollCover": [],
  "Ext.fx.layout.card.ScrollReveal": [],
  "Ext.fx.layout.card.Slide": [],
  "Ext.fx.layout.card.Style": [],
  "Ext.fx.runner.Css": [],
  "Ext.fx.runner.CssAnimation": [],
  "Ext.fx.runner.CssTransition": [],
  "Ext.layout.Abstract": [],
  "Ext.layout.Box": [],
  "Ext.layout.Card": [],
  "Ext.layout.Default": [],
  "Ext.layout.Fit": [],
  "Ext.layout.FlexBox": [],
  "Ext.layout.Float": [],
  "Ext.layout.HBox": [],
  "Ext.layout.VBox": [],
  "Ext.layout.wrapper.BoxDock": [],
  "Ext.layout.wrapper.Dock": [],
  "Ext.layout.wrapper.Inner": [],
  "Ext.mixin.Bindable": [],
  "Ext.mixin.Filterable": [],
  "Ext.mixin.Mixin": [],
  "Ext.mixin.Observable": [
    "Ext.util.Observable"
  ],
  "Ext.mixin.Selectable": [],
  "Ext.mixin.Sortable": [],
  "Ext.mixin.Templatable": [],
  "Ext.mixin.Traversable": [],
  "Ext.navigation.Bar": [],
  "Ext.navigation.View": [
    "Ext.NavigationView"
  ],
  "Ext.picker.Date": [
    "Ext.DatePicker"
  ],
  "Ext.picker.Picker": [
    "Ext.Picker"
  ],
  "Ext.picker.Slot": [
    "Ext.Picker.Slot"
  ],
  "Ext.plugin.ListPaging": [],
  "Ext.plugin.PullRefresh": [],
  "Ext.scroll.Indicator": [
    "Ext.util.Indicator"
  ],
  "Ext.scroll.Scroller": [],
  "Ext.scroll.View": [
    "Ext.util.ScrollView"
  ],
  "Ext.scroll.indicator.Abstract": [],
  "Ext.scroll.indicator.CssTransform": [],
  "Ext.scroll.indicator.Default": [],
  "Ext.scroll.indicator.ScrollPosition": [],
  "Ext.scroll.indicator.Throttled": [],
  "Ext.slider.Slider": [],
  "Ext.slider.Thumb": [],
  "Ext.slider.Toggle": [],
  "Ext.tab.Bar": [
    "Ext.TabBar"
  ],
  "Ext.tab.Panel": [
    "Ext.TabPanel"
  ],
  "Ext.tab.Tab": [
    "Ext.Tab"
  ],
  "Ext.table.Cell": [],
  "Ext.table.Row": [],
  "Ext.table.Table": [],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Collection": [],
  "Ext.util.DelayedTask": [],
  "Ext.util.Draggable": [],
  "Ext.util.Droppable": [],
  "Ext.util.Filter": [],
  "Ext.util.Format": [],
  "Ext.util.Geolocation": [
    "Ext.util.GeoLocation"
  ],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.Inflector": [],
  "Ext.util.LineSegment": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.Offset": [],
  "Ext.util.PaintMonitor": [],
  "Ext.util.Point": [],
  "Ext.util.PositionMap": [],
  "Ext.util.Region": [],
  "Ext.util.SizeMonitor": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.TapRepeater": [],
  "Ext.util.Translatable": [],
  "Ext.util.TranslatableGroup": [],
  "Ext.util.TranslatableList": [],
  "Ext.util.Wrapper": [],
  "Ext.util.paintmonitor.Abstract": [],
  "Ext.util.paintmonitor.CssAnimation": [],
  "Ext.util.paintmonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Abstract": [],
  "Ext.util.sizemonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Scroll": [],
  "Ext.util.translatable.Abstract": [],
  "Ext.util.translatable.CssPosition": [],
  "Ext.util.translatable.CssTransform": [],
  "Ext.util.translatable.Dom": [],
  "Ext.util.translatable.ScrollPosition": [],
  "Ext.viewport.Android": [],
  "Ext.viewport.Default": [],
  "Ext.viewport.Ios": [],
  "Ext.viewport.Viewport": [],
  "Kiva.controller.Loans": [],
  "Kiva.model.Loan": [],
  "Kiva.store.Loans": [],
  "Kiva.view.Detail": [],
  "Kiva.view.LoanFilter": [],
  "Kiva.view.LoansList": [],
  "Kiva.view.LoansListItem": [],
  "Kiva.view.LoansListItemCompletion": [],
  "Kiva.view.Main": [],
  "Kiva.view.detail.Information": [],
  "Kiva.view.detail.Map": [],
  "Kiva.view.detail.Schedule": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.AbstractComponent": [],
  "Ext.AbstractManager": [],
  "Ext.ActionSheet": [
    "widget.actionsheet"
  ],
  "Ext.Ajax": [],
  "Ext.Anim": [],
  "Ext.Audio": [
    "widget.audio"
  ],
  "Ext.Button": [
    "widget.button"
  ],
  "Ext.Component": [
    "widget.component"
  ],
  "Ext.ComponentManager": [],
  "Ext.ComponentQuery": [],
  "Ext.Container": [
    "widget.container"
  ],
  "Ext.Decorator": [],
  "Ext.Evented": [],
  "Ext.Img": [
    "widget.image",
    "widget.img"
  ],
  "Ext.ItemCollection": [],
  "Ext.Label": [
    "widget.label"
  ],
  "Ext.LoadMask": [
    "widget.loadmask"
  ],
  "Ext.Map": [
    "widget.map"
  ],
  "Ext.Mask": [
    "widget.mask"
  ],
  "Ext.Media": [
    "widget.media"
  ],
  "Ext.MessageBox": [],
  "Ext.Panel": [
    "widget.panel"
  ],
  "Ext.SegmentedButton": [
    "widget.segmentedbutton"
  ],
  "Ext.Sheet": [
    "widget.sheet"
  ],
  "Ext.Sortable": [],
  "Ext.Spacer": [
    "widget.spacer"
  ],
  "Ext.TaskQueue": [],
  "Ext.Template": [],
  "Ext.Title": [
    "widget.title"
  ],
  "Ext.TitleBar": [
    "widget.titlebar"
  ],
  "Ext.Toolbar": [
    "widget.toolbar"
  ],
  "Ext.Video": [
    "widget.video"
  ],
  "Ext.XTemplate": [],
  "Ext.XTemplateCompiler": [],
  "Ext.XTemplateParser": [],
  "Ext.app.Action": [],
  "Ext.app.Application": [],
  "Ext.app.Controller": [],
  "Ext.app.History": [],
  "Ext.app.Profile": [],
  "Ext.app.Route": [],
  "Ext.app.Router": [],
  "Ext.bb.CrossCut": [
    "widget.crosscut"
  ],
  "Ext.behavior.Behavior": [],
  "Ext.behavior.Draggable": [],
  "Ext.behavior.Scrollable": [],
  "Ext.behavior.Translatable": [],
  "Ext.carousel.Carousel": [
    "widget.carousel"
  ],
  "Ext.carousel.Indicator": [
    "widget.carouselindicator"
  ],
  "Ext.carousel.Infinite": [],
  "Ext.carousel.Item": [],
  "Ext.data.ArrayStore": [
    "store.array"
  ],
  "Ext.data.Batch": [],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [
    "store.direct"
  ],
  "Ext.data.Error": [],
  "Ext.data.Errors": [],
  "Ext.data.Field": [
    "data.field"
  ],
  "Ext.data.JsonP": [],
  "Ext.data.JsonStore": [
    "store.json"
  ],
  "Ext.data.Model": [],
  "Ext.data.ModelManager": [],
  "Ext.data.NodeInterface": [],
  "Ext.data.NodeStore": [
    "store.node"
  ],
  "Ext.data.Operation": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [
    "store.store"
  ],
  "Ext.data.StoreManager": [],
  "Ext.data.TreeStore": [
    "store.tree"
  ],
  "Ext.data.Types": [],
  "Ext.data.Validations": [],
  "Ext.data.association.Association": [],
  "Ext.data.association.BelongsTo": [
    "association.belongsto"
  ],
  "Ext.data.association.HasMany": [
    "association.hasmany"
  ],
  "Ext.data.association.HasOne": [
    "association.hasone"
  ],
  "Ext.data.identifier.Sequential": [
    "data.identifier.sequential"
  ],
  "Ext.data.identifier.Simple": [
    "data.identifier.simple"
  ],
  "Ext.data.identifier.Uuid": [
    "data.identifier.uuid"
  ],
  "Ext.data.proxy.Ajax": [
    "proxy.ajax"
  ],
  "Ext.data.proxy.Client": [],
  "Ext.data.proxy.Direct": [
    "proxy.direct"
  ],
  "Ext.data.proxy.JsonP": [
    "proxy.jsonp",
    "proxy.scripttag"
  ],
  "Ext.data.proxy.Kiva": [
    "proxy.kiva"
  ],
  "Ext.data.proxy.LocalStorage": [
    "proxy.localstorage"
  ],
  "Ext.data.proxy.Memory": [
    "proxy.memory"
  ],
  "Ext.data.proxy.Proxy": [
    "proxy.proxy"
  ],
  "Ext.data.proxy.Rest": [
    "proxy.rest"
  ],
  "Ext.data.proxy.Server": [
    "proxy.server"
  ],
  "Ext.data.proxy.SessionStorage": [
    "proxy.sessionstorage"
  ],
  "Ext.data.proxy.Sql": [
    "proxy.sql"
  ],
  "Ext.data.proxy.WebStorage": [],
  "Ext.data.reader.Array": [
    "reader.array"
  ],
  "Ext.data.reader.Json": [
    "reader.json"
  ],
  "Ext.data.reader.Reader": [],
  "Ext.data.reader.Xml": [
    "reader.xml"
  ],
  "Ext.data.writer.Json": [
    "writer.json"
  ],
  "Ext.data.writer.Writer": [
    "writer.base"
  ],
  "Ext.data.writer.Xml": [
    "writer.xml"
  ],
  "Ext.dataview.DataView": [
    "widget.dataview"
  ],
  "Ext.dataview.IndexBar": [],
  "Ext.dataview.List": [
    "widget.list"
  ],
  "Ext.dataview.ListItemHeader": [
    "widget.listitemheader"
  ],
  "Ext.dataview.NestedList": [
    "widget.nestedlist"
  ],
  "Ext.dataview.component.Container": [],
  "Ext.dataview.component.DataItem": [
    "widget.dataitem"
  ],
  "Ext.dataview.component.ListItem": [
    "widget.listitem"
  ],
  "Ext.dataview.element.Container": [],
  "Ext.dataview.element.List": [],
  "Ext.device.Camera": [],
  "Ext.device.Communicator": [],
  "Ext.device.Connection": [],
  "Ext.device.Contacts": [],
  "Ext.device.Device": [],
  "Ext.device.Geolocation": [],
  "Ext.device.Notification": [],
  "Ext.device.Orientation": [],
  "Ext.device.Purchases": [],
  "Ext.device.Purchases.Product": [],
  "Ext.device.Purchases.Purchase": [],
  "Ext.device.Push": [],
  "Ext.device.camera.Abstract": [],
  "Ext.device.camera.PhoneGap": [],
  "Ext.device.camera.Sencha": [],
  "Ext.device.camera.Simulator": [],
  "Ext.device.communicator.Android": [],
  "Ext.device.communicator.Default": [],
  "Ext.device.connection.Abstract": [],
  "Ext.device.connection.PhoneGap": [],
  "Ext.device.connection.Sencha": [],
  "Ext.device.connection.Simulator": [],
  "Ext.device.contacts.Abstract": [],
  "Ext.device.contacts.Sencha": [],
  "Ext.device.device.Abstract": [],
  "Ext.device.device.PhoneGap": [],
  "Ext.device.device.Sencha": [],
  "Ext.device.device.Simulator": [],
  "Ext.device.geolocation.Abstract": [],
  "Ext.device.geolocation.Sencha": [],
  "Ext.device.geolocation.Simulator": [],
  "Ext.device.notification.Abstract": [],
  "Ext.device.notification.PhoneGap": [],
  "Ext.device.notification.Sencha": [],
  "Ext.device.notification.Simulator": [],
  "Ext.device.orientation.Abstract": [],
  "Ext.device.orientation.HTML5": [],
  "Ext.device.orientation.Sencha": [],
  "Ext.device.purchases.Sencha": [],
  "Ext.device.push.Abstract": [],
  "Ext.device.push.Sencha": [],
  "Ext.direct.Event": [
    "direct.event"
  ],
  "Ext.direct.ExceptionEvent": [
    "direct.exception"
  ],
  "Ext.direct.JsonProvider": [
    "direct.jsonprovider"
  ],
  "Ext.direct.Manager": [],
  "Ext.direct.PollingProvider": [
    "direct.pollingprovider"
  ],
  "Ext.direct.Provider": [
    "direct.provider"
  ],
  "Ext.direct.RemotingEvent": [
    "direct.rpc"
  ],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [
    "direct.remotingprovider"
  ],
  "Ext.direct.Transaction": [
    "direct.transaction"
  ],
  "Ext.dom.CompositeElement": [],
  "Ext.event.Controller": [],
  "Ext.event.Dispatcher": [],
  "Ext.event.Dom": [],
  "Ext.event.Event": [],
  "Ext.event.ListenerStack": [],
  "Ext.event.Touch": [],
  "Ext.event.publisher.ComponentDelegation": [],
  "Ext.event.publisher.ComponentPaint": [],
  "Ext.event.publisher.ComponentSize": [],
  "Ext.event.publisher.Dom": [],
  "Ext.event.publisher.ElementPaint": [],
  "Ext.event.publisher.ElementSize": [],
  "Ext.event.publisher.Publisher": [],
  "Ext.event.publisher.TouchGesture": [],
  "Ext.event.recognizer.DoubleTap": [],
  "Ext.event.recognizer.Drag": [],
  "Ext.event.recognizer.HorizontalSwipe": [],
  "Ext.event.recognizer.LongPress": [],
  "Ext.event.recognizer.MultiTouch": [],
  "Ext.event.recognizer.Pinch": [],
  "Ext.event.recognizer.Recognizer": [],
  "Ext.event.recognizer.Rotate": [],
  "Ext.event.recognizer.SingleTouch": [],
  "Ext.event.recognizer.Swipe": [],
  "Ext.event.recognizer.Tap": [],
  "Ext.event.recognizer.Touch": [],
  "Ext.event.recognizer.VerticalSwipe": [],
  "Ext.field.Checkbox": [
    "widget.checkboxfield"
  ],
  "Ext.field.DatePicker": [
    "widget.datepickerfield"
  ],
  "Ext.field.Email": [
    "widget.emailfield"
  ],
  "Ext.field.Field": [
    "widget.field"
  ],
  "Ext.field.File": [
    "widget.file"
  ],
  "Ext.field.Hidden": [
    "widget.hiddenfield"
  ],
  "Ext.field.Input": [
    "widget.input"
  ],
  "Ext.field.Number": [
    "widget.numberfield"
  ],
  "Ext.field.Password": [
    "widget.passwordfield"
  ],
  "Ext.field.Radio": [
    "widget.radiofield"
  ],
  "Ext.field.Search": [
    "widget.searchfield"
  ],
  "Ext.field.Select": [
    "widget.selectfield"
  ],
  "Ext.field.Slider": [
    "widget.sliderfield"
  ],
  "Ext.field.Spinner": [
    "widget.spinnerfield"
  ],
  "Ext.field.Text": [
    "widget.textfield"
  ],
  "Ext.field.TextArea": [
    "widget.textareafield"
  ],
  "Ext.field.TextAreaInput": [
    "widget.textareainput"
  ],
  "Ext.field.Toggle": [
    "widget.togglefield"
  ],
  "Ext.field.Url": [
    "widget.urlfield"
  ],
  "Ext.form.FieldSet": [
    "widget.fieldset"
  ],
  "Ext.form.Panel": [
    "widget.formpanel"
  ],
  "Ext.fx.Animation": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Runner": [],
  "Ext.fx.State": [],
  "Ext.fx.animation.Abstract": [],
  "Ext.fx.animation.Cube": [
    "animation.cube"
  ],
  "Ext.fx.animation.Fade": [
    "animation.fade",
    "animation.fadeIn"
  ],
  "Ext.fx.animation.FadeOut": [
    "animation.fadeOut"
  ],
  "Ext.fx.animation.Flip": [
    "animation.flip"
  ],
  "Ext.fx.animation.Pop": [
    "animation.pop",
    "animation.popIn"
  ],
  "Ext.fx.animation.PopOut": [
    "animation.popOut"
  ],
  "Ext.fx.animation.Slide": [
    "animation.slide",
    "animation.slideIn"
  ],
  "Ext.fx.animation.SlideOut": [
    "animation.slideOut"
  ],
  "Ext.fx.animation.Wipe": [],
  "Ext.fx.animation.WipeOut": [],
  "Ext.fx.easing.Abstract": [],
  "Ext.fx.easing.Bounce": [],
  "Ext.fx.easing.BoundMomentum": [],
  "Ext.fx.easing.EaseIn": [
    "easing.ease-in"
  ],
  "Ext.fx.easing.EaseOut": [
    "easing.ease-out"
  ],
  "Ext.fx.easing.Linear": [
    "easing.linear"
  ],
  "Ext.fx.easing.Momentum": [],
  "Ext.fx.layout.Card": [],
  "Ext.fx.layout.card.Abstract": [],
  "Ext.fx.layout.card.Cover": [
    "fx.layout.card.cover"
  ],
  "Ext.fx.layout.card.Cube": [
    "fx.layout.card.cube"
  ],
  "Ext.fx.layout.card.Fade": [
    "fx.layout.card.fade"
  ],
  "Ext.fx.layout.card.Flip": [
    "fx.layout.card.flip"
  ],
  "Ext.fx.layout.card.Pop": [
    "fx.layout.card.pop"
  ],
  "Ext.fx.layout.card.Reveal": [
    "fx.layout.card.reveal"
  ],
  "Ext.fx.layout.card.Scroll": [
    "fx.layout.card.scroll"
  ],
  "Ext.fx.layout.card.ScrollCover": [
    "fx.layout.card.scrollcover"
  ],
  "Ext.fx.layout.card.ScrollReveal": [
    "fx.layout.card.scrollreveal"
  ],
  "Ext.fx.layout.card.Slide": [
    "fx.layout.card.slide"
  ],
  "Ext.fx.layout.card.Style": [],
  "Ext.fx.runner.Css": [],
  "Ext.fx.runner.CssAnimation": [],
  "Ext.fx.runner.CssTransition": [],
  "Ext.layout.Abstract": [],
  "Ext.layout.Box": [
    "layout.tablebox"
  ],
  "Ext.layout.Card": [
    "layout.card"
  ],
  "Ext.layout.Default": [
    "layout.auto",
    "layout.default"
  ],
  "Ext.layout.Fit": [
    "layout.fit"
  ],
  "Ext.layout.FlexBox": [
    "layout.box"
  ],
  "Ext.layout.Float": [
    "layout.float"
  ],
  "Ext.layout.HBox": [
    "layout.hbox"
  ],
  "Ext.layout.VBox": [
    "layout.vbox"
  ],
  "Ext.layout.wrapper.BoxDock": [],
  "Ext.layout.wrapper.Dock": [],
  "Ext.layout.wrapper.Inner": [],
  "Ext.mixin.Bindable": [],
  "Ext.mixin.Filterable": [],
  "Ext.mixin.Mixin": [],
  "Ext.mixin.Observable": [],
  "Ext.mixin.Selectable": [],
  "Ext.mixin.Sortable": [],
  "Ext.mixin.Templatable": [],
  "Ext.mixin.Traversable": [],
  "Ext.navigation.Bar": [],
  "Ext.navigation.View": [
    "widget.navigationview"
  ],
  "Ext.picker.Date": [
    "widget.datepicker"
  ],
  "Ext.picker.Picker": [
    "widget.picker"
  ],
  "Ext.picker.Slot": [
    "widget.pickerslot"
  ],
  "Ext.plugin.ListPaging": [
    "plugin.listpaging"
  ],
  "Ext.plugin.PullRefresh": [
    "plugin.pullrefresh"
  ],
  "Ext.scroll.Indicator": [],
  "Ext.scroll.Scroller": [],
  "Ext.scroll.View": [],
  "Ext.scroll.indicator.Abstract": [],
  "Ext.scroll.indicator.CssTransform": [],
  "Ext.scroll.indicator.Default": [],
  "Ext.scroll.indicator.ScrollPosition": [],
  "Ext.scroll.indicator.Throttled": [],
  "Ext.slider.Slider": [
    "widget.slider"
  ],
  "Ext.slider.Thumb": [
    "widget.thumb"
  ],
  "Ext.slider.Toggle": [],
  "Ext.tab.Bar": [
    "widget.tabbar"
  ],
  "Ext.tab.Panel": [
    "widget.tabpanel"
  ],
  "Ext.tab.Tab": [
    "widget.tab"
  ],
  "Ext.table.Cell": [
    "widget.tablecell"
  ],
  "Ext.table.Row": [
    "widget.tablerow"
  ],
  "Ext.table.Table": [
    "widget.table"
  ],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Collection": [],
  "Ext.util.DelayedTask": [],
  "Ext.util.Draggable": [],
  "Ext.util.Droppable": [],
  "Ext.util.Filter": [],
  "Ext.util.Format": [],
  "Ext.util.Geolocation": [],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.Inflector": [],
  "Ext.util.LineSegment": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.Offset": [],
  "Ext.util.PaintMonitor": [],
  "Ext.util.Point": [],
  "Ext.util.PositionMap": [],
  "Ext.util.Region": [],
  "Ext.util.SizeMonitor": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.TapRepeater": [],
  "Ext.util.Translatable": [],
  "Ext.util.TranslatableGroup": [],
  "Ext.util.TranslatableList": [],
  "Ext.util.Wrapper": [],
  "Ext.util.paintmonitor.Abstract": [],
  "Ext.util.paintmonitor.CssAnimation": [],
  "Ext.util.paintmonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Abstract": [],
  "Ext.util.sizemonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Scroll": [],
  "Ext.util.translatable.Abstract": [],
  "Ext.util.translatable.CssPosition": [],
  "Ext.util.translatable.CssTransform": [],
  "Ext.util.translatable.Dom": [],
  "Ext.util.translatable.ScrollPosition": [],
  "Ext.viewport.Android": [],
  "Ext.viewport.Default": [
    "widget.viewport"
  ],
  "Ext.viewport.Ios": [],
  "Ext.viewport.Viewport": [],
  "Kiva.controller.Loans": [],
  "Kiva.model.Loan": [],
  "Kiva.store.Loans": [],
  "Kiva.view.Detail": [
    "widget.detail"
  ],
  "Kiva.view.LoanFilter": [
    "widget.loanfilter"
  ],
  "Kiva.view.LoansList": [
    "widget.loanslist"
  ],
  "Kiva.view.LoansListItem": [
    "widget.loanslistitem"
  ],
  "Kiva.view.LoansListItemCompletion": [
    "widget.loanslistitemcompletion"
  ],
  "Kiva.view.Main": [
    "widget.mainview"
  ],
  "Kiva.view.detail.Information": [
    "widget.detailInformation"
  ],
  "Kiva.view.detail.Map": [
    "widget.detailMap"
  ],
  "Kiva.view.detail.Schedule": [
    "widget.detailSchedule"
  ]
});
