/*
 * File: app/view/detail/Schedule.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Kiva.view.detail.Schedule', {
    extend: 'Ext.Container',
    alias: 'widget.detailSchedule',

    config: {
        cls: 'detail-card',
        styleHtmlContent: true,
        scrollable: 'vertical',
        listeners: [
            {
                fn: 'onContainerInitialize',
                event: 'initialize'
            }
        ]
    },

    onContainerInitialize: function(component, eOpts) {
        this.setTpl(Ext.create('Ext.XTemplate',
        '<h1>Repayment Schedule</h1>',
        '<tpl for=".">',
        '<div class="payment">',
        '<div>{[this.formatDueDate(values.due_date)]} <span>${amount}</span></div>',
        '</div>',
        '</tpl>',
        {
            formatDueDate: function(date) {
                date = date.split('T')[0];

                var format = "j M Y";
                parsed = new Date(Ext.Date.parse(date, "Y-m-d"));

                return Ext.Date.format(parsed, format);
            }
        }
        ));
    }

});