/*
 * File: app/view/detail/Information.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Kiva.view.detail.Information', {
    extend: 'Ext.Container',
    alias: 'widget.detailInformation',

    config: {
        styleHtmlContent: true,
        scrollable: 'vertical',
        cls: [
            'detail-card'
        ],
        tpl: [
            '<h1>{name}</h1>',
            '<h2><tpl if="location.town">{location.town} </tpl>{location.country}</h2>',
            '<p class="overview">',
            '<strong>Activity:</strong> {activity}<br />',
            '<strong>Sector:</strong> {sector}<br />',
            '<strong>Amount requested:</strong> ${terms.loan_amount}<br />',
            '<strong>Amount funded:</strong> ${funded_amount}<br />',
            '</p>',
            '<p><strong>Overview</strong><br />{description}</p>',
            ''
        ]
    }

});